/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package orquestador.api;

import io.swagger.annotations.*;
import orquestador.model.JsonApiBodyLogin;
import orquestador.model.JsonApiBodyRequestPersona;
import orquestador.model.JsonApiBodyResponseErrors;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-08-17T14:53:38.878-05:00")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "login de usuarios", nickname = "loginPersonaPost", notes = "se envian los parametros de corroe y contraseña  se retorna la pesona si se encuentran", response = JsonApiBodyRequestPersona.class, tags={ "persona", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "logueo exito", response = JsonApiBodyRequestPersona.class),
        @ApiResponse(code = 400, message = "error al loguiar persona", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/login/persona",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<JsonApiBodyRequestPersona> loginPersonaPost(@ApiParam(value = "body" ,required=true )  @Valid @RequestBody JsonApiBodyLogin body);

}
