/**
 * Microservicio personas
 * Este micro se utiliza para gestionar el servicios de personas tanto clientes como administradores y super-administradores
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alexis.correa@accenture.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeleteRequest } from './deleteRequest';


export interface JsonApiBodyRequestDelete {
    persona: Array<DeleteRequest>;
}
