/**
 * Microservicio personas
 * Este micro se utiliza para gestionar el servicios de personas tanto clientes como administradores y super-administradores
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alexis.correa@accenture.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RegistrarRequest {
    id: string;
    nombre: string;
    apellidos: string;
    correo: string;
    contrasena: string;
    telefono: string;
    genero: string;
    rol: string;
    estado: string;
    token: string;
}
