/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.JsonApiBodyEditNegocio;
import io.swagger.model.JsonApiBodyRequestEditOferta;
import io.swagger.model.JsonApiBodyRequestPersona;
import io.swagger.model.JsonApiBodyResponseErrorsNegocio;
import io.swagger.model.JsonApiBodyResponseErrorsOferta;
import io.swagger.model.JsonApiBodyResponseErrorsPersona;
import io.swagger.model.JsonApiBodyResponseSuccessNegocio;
import io.swagger.model.JsonApiBodyResponseSuccessOferta;
import io.swagger.model.JsonApiBodyResponseSuccessPersona;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-08-23T20:32:20.792Z")

@Api(value = "editar", description = "the editar API")
public interface EditarApi {

    @ApiOperation(value = "edición de negocios", nickname = "editarNegocioPut", notes = "registro de negocios", response = JsonApiBodyResponseSuccessNegocio.class, tags={ "negocios", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "persona registrada correctamente", response = JsonApiBodyResponseSuccessNegocio.class),
        @ApiResponse(code = 400, message = "datos imcompletos o incorrectos", response = JsonApiBodyResponseErrorsNegocio.class) })
    @RequestMapping(value = "/editar/negocio",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<JsonApiBodyResponseSuccessNegocio> editarNegocioPut(@ApiParam(value = "body" ,required=true )  @Valid @RequestBody JsonApiBodyEditNegocio body);


    @ApiOperation(value = "edición de ofertas", nickname = "editarOfertaPut", notes = "registro de ofertas", response = JsonApiBodyResponseSuccessOferta.class, tags={ "ofertas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "persona registrada correctamente", response = JsonApiBodyResponseSuccessOferta.class),
        @ApiResponse(code = 400, message = "datos imcompletos o incorrectos", response = JsonApiBodyResponseErrorsOferta.class) })
    @RequestMapping(value = "/editar/oferta",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<JsonApiBodyResponseSuccessOferta> editarOfertaPut(@ApiParam(value = "body" ,required=true )  @Valid @RequestBody JsonApiBodyRequestEditOferta body);


    @ApiOperation(value = "edición de personas", nickname = "editarPersonaPut", notes = "edición de personas clientes y administradores", response = JsonApiBodyResponseSuccessPersona.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "persona registrada correctamente", response = JsonApiBodyResponseSuccessPersona.class),
        @ApiResponse(code = 400, message = "datos imcompletos o incorrectos", response = JsonApiBodyResponseErrorsPersona.class) })
    @RequestMapping(value = "/editar/persona",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<JsonApiBodyResponseSuccessPersona> editarPersonaPut(@ApiParam(value = "body" ,required=true )  @Valid @RequestBody JsonApiBodyRequestPersona body);

}
